version: "3.8"
services:
  monocloud:
    build: .
    container_name: monocloud
    image: monocloud
    volumes:
      - $HOME/.config/gcloud:/root/.config/gcloud
      - ./monocloud:/monocloud
    env_file:
      .env
