name: tests

on: pull_request

env:
  TEST_TAG: monopoly-test:latest

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install git crypt
        uses: Flydiverny/setup-git-crypt@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          target: test
          tags: ${{ env.TEST_TAG }}
          cache-from: type=gha,scope=test
          cache-to: type=gha,mode=max,scope=test

      - name: Test
        run: docker run --rm ${{ env.TEST_TAG }}
